# Chain-Independent ZK Storage Path Generator
[workspace]
members = [
    "crates/traverse-core",
    "crates/traverse-ethereum", 
    "crates/traverse-cli",
    "crates/traverse-valence",
]
resolver = "2"

# Root package to support examples
[package]
name = "traverse"
version = "0.1.0"
edition = "2021"
authors = ["Timewave Labs"]
license = "Apache-2.0"
repository = "https://github.com/timewave-computer/traverse"
homepage = "https://github.com/timewave-computer/traverse"
description = "Chain-independent ZK storage path generator for blockchain state verification"
keywords = ["zk", "blockchain", "ethereum", "storage", "proof"]
categories = ["cryptography", "development-tools"]

# Dependencies for examples
[dependencies]
traverse-core = { path = "crates/traverse-core" }
traverse-ethereum = { path = "crates/traverse-ethereum" }
traverse-valence = { path = "crates/traverse-valence" }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }

# Additional dependencies for examples
valence-coprocessor = { git = "https://github.com/timewave-computer/valence-coprocessor.git", tag = "v0.1.13", default-features = false, optional = true }
anyhow = { workspace = true, optional = true }
dotenv = { workspace = true, optional = true }

# Client feature dependencies
valence-domain-clients = { git = "https://github.com/timewave-computer/valence-domain-clients.git", branch = "main", optional = true }
alloy = { version = "0.9", features = ["providers", "network"], optional = true }
base64 = { version = "0.22", optional = true }
reqwest = { version = "0.12", features = ["json"], optional = true }

# Examples
[[example]]
name = "usdt_live_proof"
path = "examples/usdt_live_proof.rs"

[[example]]
name = "valence_integration"
path = "examples/valence_integration.rs"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Timewave Labs"]
license = "Apache-2.0"
repository = "https://github.com/timewave-computer/traverse"
homepage = "https://github.com/timewave-computer/traverse"
description = "Chain-independent ZK storage path generator for blockchain state verification"
keywords = ["zk", "blockchain", "ethereum", "storage", "proof"]
categories = ["cryptography", "development-tools"]

[workspace.dependencies]
# Core dependencies
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10", default-features = false }
keccak = { version = "0.1", default-features = false }

# CLI dependencies  
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"

# Ethereum dependencies
thiserror = "1.0"
tiny-keccak = { version = "2.0", features = ["keccak"] }
alloy = { version = "0.9", features = ["providers", "network", "rpc-types", "signer-local"] }
rlp = "0.5"
tokio = { version = "1.0", features = ["full"] }

# Test dependencies
proptest = "1.0"
tempfile = "3.0"

# Error handling
anyhow = "1.0"
dotenv = "0.15"

[features]
default = []
examples = ["dep:valence-coprocessor", "dep:anyhow", "dep:dotenv"]
client = ["traverse-ethereum/client", "dep:valence-domain-clients", "dep:alloy", "dep:base64", "dep:reqwest"] 