# Valence coprocessor integration for traverse
[package]
name = "traverse-valence"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Valence coprocessor integration for traverse ZK storage path generator"
keywords.workspace = true
categories.workspace = true

[features]
default = ["alloc"]
alloc = []
std = ["alloc"]
alloy = ["dep:alloy"]

# Valence coprocessor integration (no_std)
[dependencies]
traverse-core = { path = "../traverse-core", default-features = false }
valence-coprocessor = { git = "https://github.com/timewave-computer/valence-coprocessor.git", tag = "v0.1.13", default-features = false }
valence-coprocessor-wasm = { git = "https://github.com/timewave-computer/valence-coprocessor.git", tag = "v0.1.13", default-features = false, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true }

# Optional alloy dependencies for ABI encoding
alloy = { workspace = true, optional = true }

[dev-dependencies]
hex = { workspace = true, features = ["std"] } 